#
# Build an image for deploying the EBRAINS Validation Service
#
# To build the image, from the parent directory:
#   docker build -t validation_service_v3beta -f deployment/Dockerfile .
#
# To run the application:
#   docker run -d -p 80 \
#              -e KG_SERVICE_ACCOUNT_REFRESH_TOKEN \
#              -e KG_SERVICE_ACCOUNT_CLIENT_ID \
#              -e KG_SERVICE_ACCOUNT_SECRET \
#              validation_service_v3beta

FROM docker-registry.ebrains.eu/model-catalog/python:3.11

LABEL org.opencontainers.image.authors="Andrew Davison <andrew.davison@cnrs.fr>"

WORKDIR /code

ADD https://api.github.com/repos/HumanBrainProject/fairgraph/git/refs/heads/master fairgraph_version.json
RUN git clone https://github.com/HumanBrainProject/fairgraph.git --branch=master --single-branch
RUN pip install ./fairgraph

COPY requirements.txt.lock /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY validation_service /code/validation_service
COPY deployment/build_info.json /code/validation_service/build_info.json

RUN useradd appuser --uid 1001
USER appuser

CMD ["uvicorn", "validation_service.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80", "--timeout-keep-alive", "600"]
