# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_validation_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationtestresult',
            name='project',
            field=models.CharField(blank=True, help_text=b'Project with which this test run is associated(optional)', max_length=200),
        ),
    ]
