# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_validation_api', '0002_validationtestresult_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationtestresult',
            name='test_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_validation_api.ValidationTestCode'),
        ),
    ]
