# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_validation_api', '0003_auto_20170228_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationtestresult',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
