# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_validation_api', '0004_auto_20170517_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificmodel',
            name='brain_region',
            field=models.CharField(blank=True, choices=[(b'basal ganglia', b'Basal Ganglia'), (b'cerebellum', b'Cerebellum'), (b'cortex', b'Cortex'), (b'hippocampus', b'Hippocampus'), (b'other', b'Other')], help_text=b'brain region, if applicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='scientificmodel',
            name='cell_type',
            field=models.CharField(blank=True, choices=[(b'granule cell', b'Granule Cell'), (b'interneuron', b'Interneuron'), (b'pyramidal cell', b'Pyramidal Cell'), (b'other', b'Other')], help_text=b'cell type, for single-cell models', max_length=100),
        ),
        migrations.AlterField(
            model_name='scientificmodel',
            name='species',
            field=models.CharField(blank=True, choices=[(b'mouse', b'Mouse (Mus musculus)'), (b'rat', b'Rat (Rattus rattus)'), (b'other', b'Other')], help_text=b'species', max_length=100),
        ),
    ]
