# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('model_validation_api', '0005_auto_20170529_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificmodelinstance',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validationtestdefinition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
