export default {
    bodyBackground: "#FFFFFF",
    lightBackground: "#EFF7E5",
    darkOrange: "#FF9933",
    tableDarkHeader: "#13AC8B",
    tableHeader: "#4DC26D",
    tableDataHeader: "#EFF7E5",
    tableDataRow: "#FFFFFF",
    tableFooter: "#13AC8B",
    tableRowHoverColor: "#DCEDC8",
    tableRowSelectColor: "#FFE5A8",
    pageDetailBarColor: "#4DC26D",
    versionHeaderBarColor: "#13AC8B",
    textPrimary: "#000000",
    textSecondary: "#FFFFFF",
    instanceInfoBox: "#EFF7E5",
    metadataInfoBox: "#DCEDC8",
    buttonPrimary: "#9CE142",
    buttonSecondary: "#13AC8B",
    plotBarColor: "#FF9933",
    disabledColor: "#DCDCDC",
};