export default {
    bodyBackground: "#FFFFFF",
    lightBackground: "#FFF1CC",
    darkOrange: "#FF9933",
    tableHeader: "#FFD878",
    tableDataHeader: "#FFF1CC",
    tableDataRow: "#FFFFFF",
    tableFooter: "#FFD878",
    tableRowHoverColor: "#FFE5A8",
    tableRowSelectColor: "#FFC73B",
    textPrimary: "#000000",
    textSecondary: "#FFFFFF",
    instanceInfoBox: "#FFF1CC",
    metadataInfoBox: "#FFE5A8",
    buttonPrimary: "#FFC73B",
    buttonSecondary: "#FFD878",
    plotBarColor: "#FF9933",
    disabledColor: "#DCDCDC",
};
