# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu


#saying those already exist...
# RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip
# RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-user-agent
