
# from model_validation_api.models import (ValidationTestDefinition, 
#                         ValidationTestCode,
#                         ValidationTestResult, 
#                         ScientificModel, 
#                         ScientificModelInstance,
#                         ScientificModelImage,   
#                         Comments,
#                         Tickets,
#                         # FollowModel,
#                         Param_DataModalities,
#                         Param_TestType,
#                         Param_Species,
#                         Param_BrainRegion,
#                         Param_CellType,
#                         Param_ModelType,
#                         CollabParameters,
#                         Param_ScoreType,
#                         Param_organizations,
#                         )