name: Mirror to EBRAINS

on:
  push:
    branches: [ master, staging ]

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: syncmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/hbp-validation-framework"
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/model-validation/hbp-validation-framework.git"
          destination_branch: "master"
      - name: syncstaging
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/hbp-validation-framework"
          source_branch: "staging"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/model-validation/hbp-validation-framework.git"
          destination_branch: "staging"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/hbp-validation-framework"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/model-validation/hbp-validation-framework.git"
          destination_branch: "refs/tags/*"
